[build]
  command   = "npm run build"
  publish   = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[context."v1.x"]
  [[headers]]
    for = "/*"
    [headers.values]
      X-Robots-Tag = "noindex"
