savePrefix: ""
minimumReleaseAge: 10080
blockExoticSubdeps: true
storeDir: .pnpm-store
supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - arm64
    - x64
allowBuilds:
  esbuild: true
  sharp: true
